server:
  port: ${SERVER_PORT:8083}

spring:
  cloud:
    gcp:
      firestore:
        project-id: ${GCP_PROJECT_ID:yt2mp3-cloud-project}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
